runtime xdg.vim

call plug#begin('~/.config/vim/plugged')

Plug 'preservim/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'itchyny/lightline.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

" Set viminfo path in accordance with XDG Base Directory Specification
if empty($XDG_STATE_HOME)
    let $XDG_STATE_HOME = $HOME . '/.local/state'
endif

let s:viminfo_dir = $XDG_STATE_HOME . '/vim'
if !isdirectory(s:viminfo_dir)
    call mkdir(s:viminfo_dir, 'p', 0700)
endif

let &viminfofile = s:viminfo_dir . '/viminfo'

