ignores = ['.git', '.DS_Store']

[config]
whitelist = ['atuin', 'backup', 'btop', 'git', 'herdr', 'mise', 'starship', 'tmux', 'vim', 'zsh']

[whitelists]
atuin = ['config.toml']
vim = ['plugged', 'autoload']
zsh = [".z*", "*.zsh"]

[ignores_map]
zsh = [".zcompdump*"]
