exclude = ['.git', '.DS_Store']

[config]
include = ['atuin', 'backup', 'btop', 'git', 'herdr', 'mise', 'starship', 'tmux', 'vim', 'zsh']

[includes]
atuin = ['config.toml']
vim = ['plugged', 'autoload']
zsh = [".z*", "*.zsh"]

[excludes]
zsh = [".zcompdump*"]
