FROM rust:slim-bullseye

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    sudo curl git build-essential procps file gcc

# Create a non-root user
RUN useradd -m -s /bin/bash testuser && \
    usermod -aG sudo testuser && \
    echo "testuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER testuser
ENV USER=testuser
WORKDIR /home/testuser

# Prepare application directory
RUN mkdir -p /home/testuser/app
WORKDIR /home/testuser/app

# Cache Rust dependencies for much faster incremental builds
COPY --chown=testuser:testuser Cargo.toml Cargo.lock ./
RUN mkdir src && \
    echo "fn main() {}" > src/main.rs && \
    echo "" > src/lib.rs && \
    cargo fetch && \
    cargo build && \
    cargo test --no-run && \
    rm -rf src
